version: '3.8'

services:
  frontend:
    build:
      context: ./frontend # Directory containing your Dockerfile for httpd service
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
