name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Change if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        # Log in to Docker Hub
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
                  
        - name: Build and push Docker image
          run: |
            # Build the Docker image
            docker build -t myfrontendapp:latest .
  
            # Tag the image for Docker Hub
            docker tag myfrontendapp:latest mydockerhubusername/myfrontendapp:latest
  
            # Push the image to Docker Hub
            docker push mydockerhubusername/myfrontendapp:latest
  
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BCF32C14AA6E478283A065FBBE309F59 }}
            images: mydockerhubusername/myfrontendapp:latest
